<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="Editorial policies.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <title>Editorial policies</title>
</head>

<body>
    <?php
    include 'header.php';
    ?>

    <div class="container">



        <div class="container mt-5">
            <div class="child2">
                <h2 class="heading1">Editorial policies</h2>
                <h2 class="heading1">Table of contents</h2>
                <nav class="navbar5">
                    <div>
                        <ul>
                            <li style="margin-top: 20px;"><a href="#Overview">Overview</a></li>
                            <li style="margin-top: 20px;"><a href="#Communicate">Communicate with Respect</a></li>
                            <li style="margin-top: 20px;"><a href="#Ethics">Ethics and consent</a></li>
                            <li style="margin-top: 20px;"><a href="#Research">Research involving human embryos, gametes, and stem cells</a></li>
                            <li style="margin-top: 20px;"><a href="#Sex">Sex and gender in research (SAGER)</a></li>
                            <li style="margin-top: 20px;"><a href="#Animals">Research involving animals</a></li>
                            <li style="margin-top: 20px;"><a href="#plants">Research involving plants</a></li>
                            <li style="margin-top: 20px;"><a href="#Material">Research involving palaeontological and geological material</a></li>
                            <li style="margin-top: 20px;"><a href="#Dual">Dual Use Research of Concern</a></li>
                            <li style="margin-top: 20px;"><a href="#Standards">Standards for research in complementary and alternative medicine</a></li>
                            <li style="margin-top: 20px;"><a href="#Consent">Consent for publication</a></li>
                            <li style="margin-top: 20px;"><a href="#Trial">Trial registration</a></li>
                            <li style="margin-top: 20px;"><a href="#Availability">Availability of data and materials</a></li>
                            <li style="margin-top: 20px;"><a href="#Standardsof">Standards of reporting</a></li>
                            <li style="margin-top: 20px;"><a href="#Competing">Competing interests</a></li>
                            <li style="margin-top: 20px;"><a href="#Authorship">Authorship</a></li>
                            <li style="margin-top: 20px;"><a href="#Artificial">Artificial Intelligence (AI)</a></li>
                            <li style="margin-top: 20px;"><a href="#Citation">Citations</a></li>
                            <li style="margin-top: 20px;"><a href="#Preprint">Preprint sharing and citation</a></li>
                            <li style="margin-top: 20px;"><a href="#Duplicate">Duplicate publication</a></li>
                            <li style="margin-top: 20px;"><a href="#Communication">Communications of findings prior to publication</a></li>
                            <li style="margin-top: 20px;"><a href="#Peer">Peer review</a></li>
                            <li style="margin-top: 20px;"><a href="#Confidentiality">Confidentiality</a></li>
                            <li style="margin-top: 20px;"><a href="#Misconduct">Misconduct</a></li>
                            <li style="margin-top: 20px;"><a href="#Correction">Corrections and retractions</a></li>
                            <li style="margin-top: 20px;"><a href="#Appeal">Appeals and complaints</a></li>
                            <li style="margin-top: 20px;"><a href="#Collection">Collections and Special Issues</a></li>

                            <h2 style="margin-top: 50px; margin-left: -20px; color: #1b3051; font-family: Arial, Helvetica, sans-serif;" id="Overview">Overview<a href="editorial_policies.php" class="btn btn-success ms-2">Back to top</a></h2>
                            <div class="line1"></div>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none;"><a href="#"></a>XANA is a member of the <a href="">Committee on Publication Ethics (COPE)</a> and endorses the World <br> Association of Medical Editors (WAME) <a href="">Policy Statement on Geopolitical Intrusion on <br> Editorial Decisions.</a> BMC also endorses the International Committee of Medical Journal <br> Editors (ICMJE) <a href="">Recommendations for the Conduct, Reporting, Editing and Publication of <br> Scholarly Work in Medical Journals.</a></li>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none;"><a href="#"></a>Submission of a manuscript to a BMC journal implies that all authors have read and <br> agreed to its content and that the manuscript conforms to the journal’s policies.</li>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none;"><a href="#"></a>Springer xana remains neutral with regard to jurisdictional claims in published maps and <br> institutional affiliations. </li>

                            <h2 style="margin-top: 50px; margin-left: -20px; color: #1b3051; font-family: Arial, Helvetica, sans-serif;" id="Communicate">Communicate with Respec<a href="editorial_policies.php" class="btn btn-success ms-2">Back to top</a></h2>
                            <div class="line1"></div>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none;"><a href="#"></a>At Springer xana we believe that only through relationships based upon mutual respect can <br> we build trust and deliver quality publishing products and services to the communities we serve. <br> Our staff are expected to behave professionally and respectfully at all times when engaging with <br> authors, reviewers and readers. Likewise, we expect the same standards of behavior from <br> the academic community and the public in their interactions with our staff. We do not tolerate <br> aggressive behavior, or any form of harassment, bullying or discrimination directed against <br> Springer xana staff. We reserve the right to bring serious cases to the attention of employers <br> or local authorities, if needed, and may refuse to interact, or do business, with individuals who <br> repeatedly or seriously violate this policy.</li>

                            <h2 style="margin-top: 50px; margin-left: -20px; color: #1b3051; font-family: Arial, Helvetica, sans-serif;" id="Ethics">Ethics and consent<a href="editorial_policies.php" class="btn btn-success ms-2">Back to top</a></h2>
                            <div class="line1"></div>
                            <p style="color: #1b3051; margin-left: -20px; margin-top: 20px; font-family: Arial, Helvetica, sans-serif; font-size: 20px;">Ethics approval</p>
                            <li style="margin-top: 7px; margin-left: -20px; list-style: none;"><a href="#"></a>Research involving human participants, human material, or human data, must have been <br> performed in accordance with the <a href="#">Declaration of Helsinki</a> and must have been approved by an <br> appropriate ethics committee. A statement detailing this, including the name of the ethics <br> committee and the reference number where appropriate, must appear in all manuscripts <br> reporting such research. If a study has been granted an exemption from requiring ethics <br> approval, this should also be detailed in the manuscript (including the name of the ethics committee that granted the exemption). Further information and documentation to support this <br> should be made available to the Editor on request. Manuscripts may be rejected if the Editor <br> considers that the research has not been carried out within an appropriate ethical framework. In <br> rare cases, the Editor may contact the ethics committee for further information.</li>
                            <p style="color: #1b3051; margin-left: -20px; margin-top: 30px; font-family: Arial, Helvetica, sans-serif; font-size: 20px;">Retrospective ethics approval</p>
                            <li style="margin-top: -2px; margin-left: -20px; list-style: none;"><a href="#"></a>if a study has not been granted ethics committee approval prior to commencing, retrospective <br> ethics approval usually cannot be obtained and it may not be possible to consider the <br> manuscript for peer review. The decision on whether to proceed to peer review in such cases is <br> at the Editor's discretion.</li>
                            <p style="color: #1b3051; margin-left: -20px; margin-top: 30px; font-family: Arial, Helvetica, sans-serif; font-size: 20px;">New clinical tools and procedures</p>
                            <li style="margin-top: -10px; margin-left: -20px; list-style: none;"><a href="#"></a>Authors reporting the use of a new procedure or tool in a clinical setting, for example as a <br> technical advance or case report, must give a clear justification in the manuscript for why the <br> new procedure or tool was deemed more appropriate than usual clinical practice to meet the <br> patient’s clinical need. Such justification is not required if the new procedure is already approved <br> for clinical use at the authors’ institution. Authors will be expected to have obtained ethics <br> committee approval and informed patient consent for any experimental use of a novel <br> procedure or tool where a clear clinical advantage based on clinical need was not apparent <br> before treatment.</li>
                            <p style="color: #1b3051; margin-left: -20px; margin-top: 30px; font-family: Arial, Helvetica, sans-serif; font-size: 20px;">Consent to participate</p>
                            <li style="margin-top: -10px; margin-left: -20px; list-style: none;"><a href="#"></a>For all research involving human participants, informed consent to participate in the study <br> should be obtained from participants (or their parent or legal guardian in the case of children <br> under 16) and a statement to this effect should appear in the manuscript. For manuscripts <br> reporting studies involving vulnerable groups (for example, unconscious patients) where there is <br> the potential for coercion (for example prisoners) or where consent may not have been fully <br> informed, manuscripts will be considered at the editor’s discretion and may be referred to an <br> internal editorial oversight group for further scrutiny. Consent must be obtained for all forms of <br> personally identifiable data including biomedical, clinical, and biometric data. In the case of <br> articles describing human transplantation studies, authors must include a statement declaring <br> that no organs/tissues were obtained from prisoners and must also name the <br> institution(s)/clinic(s)/department(s) via which organs/tissues were obtained. Documentary <br> evidence of consent must be supplied if requested.</li>
                            <h2 style="margin-top: 50px; margin-left: -20px; color: #1b3051; font-family: Arial, Helvetica, sans-serif;">Ethics and consent<a href="editorial_policies.php" class="btn btn-success ms-2">Back to top</a></h2>
                            <div class="line1"></div>
                            <p style="color: #1b3051; margin-left: -20px; margin-top: 20px; font-family: Arial, Helvetica, sans-serif; font-size: 20px;">Ethics approval</p>
                            <li style="margin-top: 7px; margin-left: -20px; list-style: none;"><a href="#"></a>Research involving human participants, human material, or human data, must have been <br> performed in accordance with the Declaration of Helsinki and must have been approved by an <br> appropriate ethics committee. A statement detailing this, including the name of the ethics <br> committee and the reference number where appropriate, must appear in all manuscripts <br> reporting such research. If a study has been granted an exemption from requiring ethics <br> approval, this should also be detailed in the manuscript (including the name of the ethics committee that granted the exemption). Further information and documentation to support this <br> should be made available to the Editor on request. Manuscripts may be rejected if the Editor <br> considers that the research has not been carried out within an appropriate ethical framework. In <br> rare cases, the Editor may contact the ethics committee for further information.</li>

                            <h2 style="margin-top: 50px; margin-left: -20px; color: #1b3051; font-family: Arial, Helvetica, sans-serif;" id="Research">Research involving human embryos, gametes, and stem <br> cells<a href="editorial_policies.php" class="btn btn-success ms-2">Back to top</a></h2>
                            <div class="line1"></div>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none;"><a href="#"></a>Manuscripts that report experiments involving the use of human embryos and gametes, human <br> embryonic stem cells and related materials, and clinical applications of stem cells must include <br> confirmation that all experiments were performed in accordance with relevant guidelines and <br> regulations (See also <a href="">Ethics and Consent</a>)</li>
                            <li style="margin-top: 25px; margin-left: -20px; list-style: none;"><a href="#"></a>The manuscript should include an ethics statement identifying the institutional and/or national <br> research ethics committee (including the name of the ethics committee) approving the <br> experiments and describing any relevant details. Authors should confirm that informed consent <br> (See also <a href="">Ethics and Consent</a> and <a href="">Consent for publication</a>) was obtained from all recipients <br> and/or donors of cells or tissues, where necessary, and describe the conditions of donation <br> of materials for research, such as human embryos or gametes. Copies of approval and redacted <br> consent documents may be requested by the Editor.</li>
                            <li style="margin-top: 25px; margin-left: -20px; list-style: none;"><a href="#"></a>We encourage authors to follow the principles laid out in the <a href="">2016 ISSCR Guidelines for Stem <br> Cell Research and Clinical Translation.</a></li>
                            <li style="margin-top: 25px; margin-left: -20px; list-style: none;"><a href="#"></a>in deciding whether to publish papers describing modifications of the human germline, the <br> Editors are guided by safety considerations, compliance with applicable regulations, as well as <br> the status of the societal debate on the implications of such modifications for future <br> generations. In case of concerns regarding a particular type of study the Editor may seek advice <br> from the Springer xana Research Integrity Group.</li>
                            <li style="margin-top: 25px; margin-left: -20px; list-style: none;"><a href="#"></a>The decision to publish a paper is the responsibility of the Editor-in-Chief of the Journal.</li>

                            <h2 style="margin-top: 50px; margin-left: -20px; color: #1b3051; font-family: Arial, Helvetica, sans-serif;" id="Sex">Sex and gender in research (SAGER)<a href="editorial_policies.php" class="btn btn-success ms-2">Back to top</a></h2>
                            <div class="line1"></div>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none;"><a href="#"></a>We encourage our authors to follow the <a href="">‘Sex and Gender Equity in Research – SAGER – <br> guidelines’</a> and to include sex and gender considerations where relevant. Authors should use the <br> terms sex (biological attribute) and gender (shaped by social and cultural circumstances) <br> carefully in order to avoid confusing both terms. Article titles and/or abstracts should indicate <br> clearly what sex(es) the study applies to. Authors should also describe in the background, <br> whether sex and/or gender differences may be expected; report how sex and/or gender were <br> accounted for in the design of the study; provide disaggregated data by sex and/or gender, where appropriate; and discuss respective results. If a sex and/or gender analysis was not <br> conducted, the rationale should be given in the Discussion. We suggest that our authors consult <br> the full guidelines before submission.</li>
                            <li style="margin-top: 30px; margin-left: -10px;"><a href="#"></a><em> <strong>Definition of Sex and Gender</strong></em> (taken from <a href="">Office of Research in Women’s Health, NIH</a>).</li>
                            <li style="margin-top: 10px; margin-left: -10px;"><a href="#"></a><em> <strong>Sex</strong></em> - refers to biological differences between females and males, including chromosomes, sex organs, and endogenous hormonal profiles.</li>
                            <li style="margin-top: 10px; margin-left: -10px;"><a href="#"></a><em> <strong>Gender</strong></em>- refers to socially constructed and enacted roles and behaviors which occur in a historical and cultural context and vary across societies and over time.</li>
                            <li style="margin-top: 10px; margin-left: -10px;"><a href="#"></a><em> <strong>Applications of the guidelines:</strong></em> These guidelines apply to studies involving humans, vertebrate animal and cell lines.</li>

                            <h2 style="margin-top: 50px; margin-left: -20px; color: #1b3051; font-family: Arial, Helvetica, sans-serif;" id="Animals">Research involving animals<a href="editorial_policies.php" class="btn btn-success ms-2">Back to top</a></h2>
                            <div class="line1"></div>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none;"><a href="#"></a>Experimental research on vertebrates or any regulated invertebrates must comply with <br> institutional, national, or international guidelines, and where available should have been <br> approved by an appropriate ethics committee. The International Council for Laboratory Animal <br> Science (ICLAS) has published ethical guidelines.</li>
                            <li style="margin-top: 30px; margin-left: -20px; list-style: none"><a href="#"></a>A statement detailing compliance with relevant guidelines (e.g. the revised Animals (Scientific <br> Procedures) Act 1986 in the UK and Directive 2010/63/EU in Europe) and/or ethical approval <br> (including the name of the ethics committee and the reference number where appropriate) must <br> be included in the manuscript. If a study has been granted an exemption from requiring ethics <br> approval, this should also be detailed in the manuscript (including the name of the ethics <br> committee that granted the exemption and the reasons for the exemption). The Editor will take <br> account of animal welfare issues and reserves the right to reject a manuscript, especially if the <br> research involves protocols that are inconsistent with commonly accepted norms of animal <br> research. In rare cases, the Editor may contact the ethics committee for further information.</li>
                            <li style="margin-top: 30px; margin-left: -20px; list-style: none"><a href="#"></a>Manuscripts presenting studies that have employed anesthesia or euthanasia methods <br> inconsistent with the commonly accepted norms of veterinary best practice (e.g. chloral hydrate, <br> ether, and chloroform) will not be considered. Decisions to not consider manuscripts presenting <br> such anesthesia or euthanasia methods are independent of the approving ethics committee and <br> any previously published work. We recommend that authors consult the American Veterinary <br> Medical Association (AVMA) Guidelines for the Euthanasia of Animals (2020), as a comprehensive <br> resource for guidance on veterinary best practice for the anesthesia and euthanasia of animals</li>
                            <li style="margin-top: 30px; margin-left: -20px; list-style: none"><a href="#"></a>For experimental studies involving client-owned animals, authors must also document informed <br> consent from the client or owner and adherence to a high standard (best practice) of veterinary <br> care.</li>
                            <li style="margin-top: 30px; margin-left: -20px; list-style: none"><a href="#"></a>Field studies and other non-experimental research on animals must comply with institutional, <br> national, or international guidelines, and where available should have been approved by an <br> appropriate ethics committee. A statement detailing compliance with relevant guidelines and/or <br> appropriate permissions or licences must be included in the manuscript. We recommend that <br> authors comply with the IUCN Policy Statement on Research Involving Species at Risk of <br> Extinction and the Convention on the Trade in Endangered Species of Wild Fauna and Flora.</li>

                            <h2 style="margin-top: 50px; margin-left: -20px; color: #1b3051; font-family: Arial, Helvetica, sans-serif;" id="plants">Research involving plants<a href="editorial_policies.php" class="btn btn-success ms-2">Back to top</a></h2>
                            <div class="line1"></div>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none;"><a href="#"></a>Experimental research and field studies on plants (either cultivated or wild), including the <br> collection of plant material, must comply with relevant institutional, <br> national, and international guidelines and legislation. </li>
                            <li style="margin-top: 30px; margin-left: -20px; list-style: none"><a href="#"></a>Manuscripts should include a statement specifying the appropriate permissions and/or licences <br> for collection of plant or seed specimens. We recommend that authors comply with the IUCN <br> Policy Statement on Research Involving Species at Risk of Extinction and the Convention on the <br>Trade in Endangered Species of Wild Fauna and Flora.</li>
                            <li style="margin-top: 30px; margin-left: -20px; list-style: none"><a href="#"></a>To support reproducibility, voucher specimens for all wild plants described in a manuscript must <br> be deposited in a public herbarium or other public collection that provides access to deposited <br> material. Information on the voucher specimen and who identified it must be included in <br> the manuscript.</li>
                            <h2 style="margin-top: 30px; margin-left: -20px; color: #1b3051; font-family: Arial, Helvetica, sans-serif;" id="Material">Research involving palaeontological and <br>geological material<a href="editorial_policies.php" class="btn btn-success ms-2">Back to top</a>></h2>
                            <div class="line1"></div>
                            <li style="margin-top: 30px; margin-left: -20px; list-style: none;"><a href="#"></a>Details of palaeontological specimens and geological samples should include clear provenance <br> information to ensure full transparency of the research.</li>
                            <li style="margin-top: 30px; margin-left: -20px; list-style: none"><a href="#"></a>It is recognized that precise provenance information may not be available for older museum <br> collections. In circumstances where providing specific provenance information may compromise <br> the security of palaeontological or geological sites it may be appropriate to exclude detailed <br> locality information.</li>
                            <li style="margin-top: 30px; margin-left: -20px; list-style: none"><a href="#"></a>Samples must always be collected and exported in a responsible manner and in accordance with <br> applicable local and national laws. Any submission detailing new material should include <br> information regarding the requisite permissions obtained and the issuing authority. Authors may <br> be required to provide specific supporting documentation upon request. </li>
                            <li style="margin-top: 30px; margin-left: -20px; list-style: none"><a href="#"></a>Type, figured and cited palaeontological specimens, should be deposited in a recognised <br> museum or collection to permit free access by other researchers in perpetuity. Sufficient <br> information on the repository, including the assigned unique catalogue numbers (where <br> applicable), should be provided to allow the specimens to be traced.</li>
                            <li style="margin-top: 30px; margin-left: -20px; list-style: none"><a href="#"></a>We encourage deposition of 3-D scans of fossil specimens (where appropriate) within a <br> permanent, accessible repository to facilitate study by the scientific community.</li>
                            <li style="margin-top: 30px; margin-left: -20px; list-style: none"><a href="#"></a>Springer xana requires that submitted content adheres to the United Nations Educational,<br> Scientific and Cultural Organization (UNESCO) normative instruments for the protection of <br> cultural heritage, and Resolutions, Motions, guidance and other statements of the International <br> Union for the Conservation of xana (IUCN).</li>

                            <h2 style="margin-top: 40px; margin-left: -20px; color: #1b3051; font-family: Arial, Helvetica, sans-serif;" id="Dual">Dual Use Research of Concern<a href="editorial_policies.php" class="btn btn-success ms-2">Back to top</a></h2>
                            <div class="line1"></div>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none;"><a href="#"></a>Some manuscripts provide information that could be directly misapplied to pose a significant <br> threat to public health, safety or security, agricultural crops and other plants, animals, or the <br> environment. For such information to be published, the benefit to the research community, <br> society, or to public health, must outweigh any risks. We reserve the right to take expert advice <br> in cases where we believe that concerns may arise, and we may require a manuscript to undergo <br> peer review specifically to assess the dual use risk. Where the risk of misuse outweighs any <br> potential benefit, publication is declined; published content may be corrected, retracted or <br> removed</li>
                            <li style="margin-top: 30px; margin-left: -20px; list-style: none"><a href="#"></a>Researchers are expected to comply with their institutional and funder’s requirements, as well as <br> any national regulations. They should be aware of dual-use concerns related to their work and <br> take steps to minimize misuse of their research. Such concerns include, but are not limited to, <br> biosecurity, nuclear and chemical threats. Where relevant regulations exist, authors should <br> disclose whether their study is subject to consideration as dual use research of concern; if it is, <br> the manuscript should report the authority granting approval and reference number for the <br> regulatory approval. When the study reports material that can be harmful outside the laboratory <br> context, the manuscript should describe appropriate containment (e.g. biosafety) procedures.</li>
                            <li style="margin-top: 30px; margin-left: -20px; list-style: none"><a href="#"></a>We recognize the widespread view that openness in science helps to alert society to potential <br> threats and to defend against them, and we anticipate that only very rarely will the risks be <br> perceived as outweighing the benefits of publishing a paper that has otherwise been deemed <br> appropriate for publication.</li>

                            <h2 style="margin-top: 40px; margin-left: -20px; color: #1b3051; font-family: Arial, Helvetica, sans-serif;" id="Standard">Standards for research in complementary and alternative <br> medicine<a href="editorial_policies.php" class="btn btn-success ms-2">Back to top</a></h2>
                            <div class="line1"></div>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none;"><a href="#"></a>pringer xana journals are committed to evidence-based research. We believe that <br> Complementary and Alternative Medicine (CAM) research should be held to the same standards <br> and evidence threshold as those of medicine research.</li>
                            <li style="margin-top: 5px; margin-left: -20px; list-style: none"><a href="#"></a>We welcome manuscripts for submission which meet the following clinical research standards:</li>
                            <li style="margin-top: 5px; margin-left: -20px;"><a href="#"></a>Clinical research manuscripts that comply with international and national standards for such <br> work (such as the Declaration of Helsinki or relevant Governmental regulation e.g. the UK’s The <br> Medicines for Human Use (Clinical Trials) Regulations).</li>
                            <li style="margin-top: 5px; margin-left: -20px;"><a href="#"></a>Studies which are adequately controlled (be that compared to a placebo or conventional <br> medicine), blinded (where appropriate), randomised and of sufficient statistical power to <br> confidentially and accurately interpret the effect reported. Studies reporting a CAM <br> treatment/technique compared only to another CAM treatment/technique are not sufficient to <br> test the efficacy of the CAM treatment in question. Studies in which a conventional treatment <br> is supplemented with a CAM technique are only valid if compared to the same conventional treatment supplemented with a placebo.</li>
                            <li style="margin-top: 5px; margin-left: -20px;"><a href="#"></a>CAM treatments/techniques tested on animal models and/or human patients: It is unethical <br> for such work, on humans or animals, to have taken place without adequate prior evidence <br> that the treatment/technique shows some potential of being therapeutic. Manuscripts must <br> include evidence that takes the form of objective, measurable data from previously published <br> peer reviewed literature which adheres to scientific principles (for instance in vitro or cellular <br> work). Other forms of evidence are not valid. Manuscripts describing work lacking this <br> evidence will not be considered on ethical grounds.</li>
                            <h2 style="margin-top: 40px; margin-left: -20px; color: #1b3051; font-family: Arial, Helvetica, sans-serif;" id="Consent">Consent for publication<a href="editorial_policies.php" class="btn btn-success ms-2">Back to top</a></h2>
                            <div class="line1"></div>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none;"><a href="#"></a>For all manuscripts that include details, images, or videos relating to an individual person, written informed consent for the publication of these details must be obtained from that person (or their parent or legal guardian in the case of children under 18). The consent must be for publication of their details under the relevant Creative Commons license (such that they will be freely available on the internet). If the person has died, consent for publication must be obtained from their next of kin. The manuscript must include a statement that written informed consent for publication was obtained.</li>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none"><a href="#"></a>Human Research Participant Publication Approval Templates: English / German - can be used to obtain consent from human research participants/patients where there may be identifiable information and/or media. The consent form must state that the details/images/videos will be freely available on the internet and may be seen by the general public.</li>
                            <li style="margin-top: 20px; margin-left: -20px;list-style: none;"><a href="#"></a>In cases where images are entirely unidentifiable and there are no details on individuals reported within the manuscript, consent for publication of images may not be required. The final decision on whether consent to publish is required lies with the Editor.</li>
                            <li style="margin-top: 20px; margin-left: -20px;list-style: none;"><a href="#"></a>Further information, including Third Party Rights for dissemination, is available on the Springer xana pages.</li>
                            <h2 style="margin-top: 40px; margin-left: -20px; color: #1b3051; font-family: Arial, Helvetica, sans-serif;" id="Trial">Trial registration<a href="editorial_policies.php" class="btn btn-success ms-2">Back to top</a></h2>
                            <div class="line1"></div>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none;"><a href="#"></a>BMC supports initiatives to improve reporting of clinical trials. This includes prospective registration of clinical trials in suitable publicly available databases. In line with ICMJE guidelines, BMC requires registration of all clinical trials that are reported in manuscripts submitted to its journals.</li>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none"><a href="#"></a>The ICMJE uses the World Health Organization (WHO) definition of a clinical trial, which is "any research study that prospectively assigns human participants or groups of humans to one or more health-related interventions to evaluate the effects on health outcomes". This definition includes phase I to IV trials. The ICMJE defines health-related interventions as "any intervention used to modify a biomedical or health-related outcome" and health-related outcomes as "any biomedical or health-related measures obtained in patients or participants". Authors who are unsure whether their trial needs registering should consult the ICMJE FAQs for further information.</li>
                            <li style="margin-top: 20px; margin-left: -20px;list-style: none;"><a href="#"></a>Suitable publicly available registries are those listed on the ICMJE website as well as any of the primary registries that participate in the WHO International Clinical Trials Registry Platform, including the ISRCTN registry, which is administered and published by BMC.</li>
                            <li style="margin-top: 20px; margin-left: -20px;list-style: none;"><a href="#"></a>The trial registration number (TRN) and date of registration should be included as the last line of the manuscript abstract.</li>
                            <h2 style="margin-top: 40px; margin-left: -20px; color: #1b3051; font-family: Arial, Helvetica, sans-serif;" id="Consent">Consent for publication<a href="editorial_policies.php" class="btn btn-success ms-2">Back to top</a></h2>
                            <div class="line1"></div>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none;"><a href="#"></a>For all manuscripts that include details, images, or videos relating to an individual person, written informed consent for the publication of these details must be obtained from that person (or their parent or legal guardian in the case of children under 18). The consent must be for publication of their details under the relevant Creative Commons license (such that they will be freely available on the internet). If the person has died, consent for publication must be obtained from their next of kin. The manuscript must include a statement that written informed consent for publication was obtained.</li>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none"><a href="#"></a>Human Research Participant Publication Approval Templates: English / German - can be used to obtain consent from human research participants/patients where there may be identifiable information and/or media. The consent form must state that the details/images/videos will be freely available on the internet and may be seen by the general public.</li>
                            <li style="margin-top: 20px; margin-left: -20px;list-style: none;"><a href="#"></a>In cases where images are entirely unidentifiable and there are no details on individuals reported within the manuscript, consent for publication of images may not be required. The final decision on whether consent to publish is required lies with the Editor.</li>
                            <li style="margin-top: 20px; margin-left: -20px;list-style: none;"><a href="#"></a>Further information, including Third Party Rights for dissemination, is available on the Springer xana pages.</li>
                            <h2 style="margin-top: 40px; margin-left: -20px; color: #1b3051; font-family: Arial, Helvetica, sans-serif;" id="Availability">Availability of data and materials<a href="editorial_policies.php" class="btn btn-success ms-2">Back to top</a></h2>
                            <div class="line1"></div>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none;"><a href="#"></a>Submission of a manuscript to a BMC journal implies that materials described in the manuscript, including all relevant raw data, will be freely available to any scientist wishing to use them for non-commercial purposes, without breaching participant confidentiality.</li>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none"><a href="#"></a>For all journals, BMC strongly encourages that all datasets on which the conclusions of the paper rely should be available to readers, and where there is a community established norm for data sharing, BMC mandates data deposition (for data types with required deposition, see below). </li>
                            <li style="margin-top: 20px; margin-left: -20px;list-style: none;"><a href="#"></a>We encourage authors to ensure that their datasets are either deposited in publicly available repositories (where available and appropriate) or presented in the main manuscript or additional supporting files, in machine-readable format (such as spreadsheets rather than PDFs) whenever possible. Please see the Data repository guidance page for further information. For several journals, deposition of the data on which the conclusions of the manuscript rely is required. Please check the individual journal’s Submission Guidelines for more information.</li>
                            <li style="margin-top: 20px; margin-left: -20px;list-style: none;"><a href="#"></a>Authors who need help understanding our data sharing policies, finding a suitable data repository, or organising and sharing research data can access our Author Support portal for additional guidance.</li>
                            <h2 style="margin-top: 40px; margin-left: -20px; color: #1b3051; font-family: Arial, Helvetica, sans-serif;" id="Standardsof">Standards of reporting<a href="editorial_policies.php" class="btn btn-success ms-2">Back to top</a></h2>
                            <div class="line1"></div>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none;"><a href="#"></a>Submission of a manuscript to a BMC journal implies that materials described in the manuscript, including all relevant raw data, will be freely available to any scientist wishing to use them for non-commercial purposes, without breaching participant confidentiality.</li>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none"><a href="#"></a>For all journals, BMC strongly encourages that all datasets on which the conclusions of the paper rely should be available to readers, and where there is a community established norm for data sharing, BMC mandates data deposition (for data types with required deposition, see below). </li>
                            <li style="margin-top: 20px; margin-left: -20px;list-style: none;"><a href="#"></a>We encourage authors to ensure that their datasets are either deposited in publicly available repositories (where available and appropriate) or presented in the main manuscript or additional supporting files, in machine-readable format (such as spreadsheets rather than PDFs) whenever possible. Please see the Data repository guidance page for further information. For several journals, deposition of the data on which the conclusions of the manuscript rely is required. Please check the individual journal’s Submission Guidelines for more information.</li>
                            <li style="margin-top: 20px; margin-left: -20px;list-style: none;"><a href="#"></a>Authors who need help understanding our data sharing policies, finding a suitable data repository, or organising and sharing research data can access our Author Support portal for additional guidance.</li>
                            <h2 style="margin-top: 40px; margin-left: -20px; color: #1b3051; font-family: Arial, Helvetica, sans-serif;" id="Describing">Describing new taxa<a href="editorial_policies.php" class="btn btn-success ms-2">Back to top</a></h2>
                            <div class="line1"></div>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none;"><a href="#"></a>Submission of a manuscript to a BMC journal implies that materials described in the manuscript, including all relevant raw data, will be freely available to any scientist wishing to use them for non-commercial purposes, without breaching participant confidentiality.</li>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none"><a href="#"></a>For all journals, BMC strongly encourages that all datasets on which the conclusions of the paper rely should be available to readers, and where there is a community established norm for data sharing, BMC mandates data deposition (for data types with required deposition, see below). </li>
                            <li style="margin-top: 20px; margin-left: -20px;list-style: none;"><a href="#"></a>We encourage authors to ensure that their datasets are either deposited in publicly available repositories (where available and appropriate) or presented in the main manuscript or additional supporting files, in machine-readable format (such as spreadsheets rather than PDFs) whenever possible. Please see the Data repository guidance page for further information. For several journals, deposition of the data on which the conclusions of the manuscript rely is required. Please check the individual journal’s Submission Guidelines for more information.</li>
                            <li style="margin-top: 20px; margin-left: -20px;list-style: none;"><a href="#"></a>Authors who need help understanding our data sharing policies, finding a suitable data repository, or organising and sharing research data can access our Author Support portal for additional guidance.</li>
                            <h2 style="margin-top: 40px; margin-left: -20px; color: #1b3051; font-family: Arial, Helvetica, sans-serif;" id="Competing">Competing interests<a href="editorial_policies.php" class="btn btn-success ms-2">Back to top</a></h2>
                            <div class="line1"></div>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none;"><a href="#"></a>Submission of a manuscript to a BMC journal implies that materials described in the manuscript, including all relevant raw data, will be freely available to any scientist wishing to use them for non-commercial purposes, without breaching participant confidentiality.</li>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none"><a href="#"></a>For all journals, BMC strongly encourages that all datasets on which the conclusions of the paper rely should be available to readers, and where there is a community established norm for data sharing, BMC mandates data deposition (for data types with required deposition, see below). </li>
                            <li style="margin-top: 20px; margin-left: -20px;list-style: none;"><a href="#"></a>We encourage authors to ensure that their datasets are either deposited in publicly available repositories (where available and appropriate) or presented in the main manuscript or additional supporting files, in machine-readable format (such as spreadsheets rather than PDFs) whenever possible. Please see the Data repository guidance page for further information. For several journals, deposition of the data on which the conclusions of the manuscript rely is required. Please check the individual journal’s Submission Guidelines for more information.</li>
                            <li style="margin-top: 20px; margin-left: -20px;list-style: none;"><a href="#"></a>Authors who need help understanding our data sharing policies, finding a suitable data repository, or organising and sharing research data can access our Author Support portal for additional guidance.</li>
                            <h2 style="margin-top: 40px; margin-left: -20px; color: #1b3051; font-family: Arial, Helvetica, sans-serif;" id="Authorship">Authorship<a href="editorial_policies.php" class="btn btn-success ms-2">Back to top</a></h2>
                            <div class="line1"></div>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none;"><a href="#"></a>Submission of a manuscript to a BMC journal implies that materials described in the manuscript, including all relevant raw data, will be freely available to any scientist wishing to use them for non-commercial purposes, without breaching participant confidentiality.</li>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none"><a href="#"></a>For all journals, BMC strongly encourages that all datasets on which the conclusions of the paper rely should be available to readers, and where there is a community established norm for data sharing, BMC mandates data deposition (for data types with required deposition, see below). </li>
                            <li style="margin-top: 20px; margin-left: -20px;list-style: none;"><a href="#"></a>We encourage authors to ensure that their datasets are either deposited in publicly available repositories (where available and appropriate) or presented in the main manuscript or additional supporting files, in machine-readable format (such as spreadsheets rather than PDFs) whenever possible. Please see the Data repository guidance page for further information. For several journals, deposition of the data on which the conclusions of the manuscript rely is required. Please check the individual journal’s Submission Guidelines for more information.</li>
                            <li style="margin-top: 20px; margin-left: -20px;list-style: none;"><a href="#"></a>Authors who need help understanding our data sharing policies, finding a suitable data repository, or organising and sharing research data can access our Author Support portal for additional guidance.</li>
                            <h2 style="margin-top: 40px; margin-left: -20px; color: #1b3051; font-family: Arial, Helvetica, sans-serif;" id="Artificial">Artificial Intelligence (AI)<a href="editorial_policies.php" class="btn btn-success ms-2">Back to top</a></h2>
                            <div class="line1"></div>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none;"><a href="#"></a>Submission of a manuscript to a BMC journal implies that materials described in the manuscript, including all relevant raw data, will be freely available to any scientist wishing to use them for non-commercial purposes, without breaching participant confidentiality.</li>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none"><a href="#"></a>For all journals, BMC strongly encourages that all datasets on which the conclusions of the paper rely should be available to readers, and where there is a community established norm for data sharing, BMC mandates data deposition (for data types with required deposition, see below). </li>
                            <li style="margin-top: 20px; margin-left: -20px;list-style: none;"><a href="#"></a>We encourage authors to ensure that their datasets are either deposited in publicly available repositories (where available and appropriate) or presented in the main manuscript or additional supporting files, in machine-readable format (such as spreadsheets rather than PDFs) whenever possible. Please see the Data repository guidance page for further information. For several journals, deposition of the data on which the conclusions of the manuscript rely is required. Please check the individual journal’s Submission Guidelines for more information.</li>
                            <li style="margin-top: 20px; margin-left: -20px;list-style: none;"><a href="#"></a>Authors who need help understanding our data sharing policies, finding a suitable data repository, or organising and sharing research data can access our Author Support portal for additional guidance.</li>
                            <h2 style="margin-top: 40px; margin-left: -20px; color: #1b3051; font-family: Arial, Helvetica, sans-serif;" id="Citations">Citations<a href="editorial_policies.php" class="btn btn-success ms-2">Back to top</a></h2>
                            <div class="line1"></div>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none;"><a href="#"></a>Submission of a manuscript to a BMC journal implies that materials described in the manuscript, including all relevant raw data, will be freely available to any scientist wishing to use them for non-commercial purposes, without breaching participant confidentiality.</li>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none"><a href="#"></a>For all journals, BMC strongly encourages that all datasets on which the conclusions of the paper rely should be available to readers, and where there is a community established norm for data sharing, BMC mandates data deposition (for data types with required deposition, see below). </li>
                            <li style="margin-top: 20px; margin-left: -20px;list-style: none;"><a href="#"></a>We encourage authors to ensure that their datasets are either deposited in publicly available repositories (where available and appropriate) or presented in the main manuscript or additional supporting files, in machine-readable format (such as spreadsheets rather than PDFs) whenever possible. Please see the Data repository guidance page for further information. For several journals, deposition of the data on which the conclusions of the manuscript rely is required. Please check the individual journal’s Submission Guidelines for more information.</li>
                            <li style="margin-top: 20px; margin-left: -20px;list-style: none;"><a href="#"></a>Authors who need help understanding our data sharing policies, finding a suitable data repository, or organising and sharing research data can access our Author Support portal for additional guidance.</li>
                            <h2 style="margin-top: 40px; margin-left: -20px; color: #1b3051; font-family: Arial, Helvetica, sans-serif;" id="Preprint">Preprint sharing and citation<a href="editorial_policies.php" class="btn btn-success ms-2">Back to top</a></h2>
                            <div class="line1"></div>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none;"><a href="#"></a>Submission of a manuscript to a BMC journal implies that materials described in the manuscript, including all relevant raw data, will be freely available to any scientist wishing to use them for non-commercial purposes, without breaching participant confidentiality.</li>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none"><a href="#"></a>For all journals, BMC strongly encourages that all datasets on which the conclusions of the paper rely should be available to readers, and where there is a community established norm for data sharing, BMC mandates data deposition (for data types with required deposition, see below). </li>
                            <li style="margin-top: 20px; margin-left: -20px;list-style: none;"><a href="#"></a>We encourage authors to ensure that their datasets are either deposited in publicly available repositories (where available and appropriate) or presented in the main manuscript or additional supporting files, in machine-readable format (such as spreadsheets rather than PDFs) whenever possible. Please see the Data repository guidance page for further information. For several journals, deposition of the data on which the conclusions of the manuscript rely is required. Please check the individual journal’s Submission Guidelines for more information.</li>
                            <li style="margin-top: 20px; margin-left: -20px;list-style: none;"><a href="#"></a>Authors who need help understanding our data sharing policies, finding a suitable data repository, or organising and sharing research data can access our Author Support portal for additional guidance.</li>
                            <h2 style="margin-top: 40px; margin-left: -20px; color: #1b3051; font-family: Arial, Helvetica, sans-serif;" id="Duplicate">Duplicate publication<a href="editorial_policies.php" class="btn btn-success ms-2">Back to top</a></h2>
                            <div class="line1"></div>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none;"><a href="#"></a>Submission of a manuscript to a BMC journal implies that materials described in the manuscript, including all relevant raw data, will be freely available to any scientist wishing to use them for non-commercial purposes, without breaching participant confidentiality.</li>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none"><a href="#"></a>For all journals, BMC strongly encourages that all datasets on which the conclusions of the paper rely should be available to readers, and where there is a community established norm for data sharing, BMC mandates data deposition (for data types with required deposition, see below). </li>
                            <li style="margin-top: 20px; margin-left: -20px;list-style: none;"><a href="#"></a>We encourage authors to ensure that their datasets are either deposited in publicly available repositories (where available and appropriate) or presented in the main manuscript or additional supporting files, in machine-readable format (such as spreadsheets rather than PDFs) whenever possible. Please see the Data repository guidance page for further information. For several journals, deposition of the data on which the conclusions of the manuscript rely is required. Please check the individual journal’s Submission Guidelines for more information.</li>
                            <li style="margin-top: 20px; margin-left: -20px;list-style: none;"><a href="#"></a>Authors who need help understanding our data sharing policies, finding a suitable data repository, or organising and sharing research data can access our Author Support portal for additional guidance.</li>
                            <h2 style="margin-top: 40px; margin-left: -20px; color: #1b3051; font-family: Arial, Helvetica, sans-serif;" id="Communications">Communications of findings prior to publication<a href="editorial_policies.php" class="btn btn-success ms-2">Back to top</a></h2>
                            <div class="line1"></div>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none;"><a href="#"></a>Submission of a manuscript to a BMC journal implies that materials described in the manuscript, including all relevant raw data, will be freely available to any scientist wishing to use them for non-commercial purposes, without breaching participant confidentiality.</li>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none"><a href="#"></a>For all journals, BMC strongly encourages that all datasets on which the conclusions of the paper rely should be available to readers, and where there is a community established norm for data sharing, BMC mandates data deposition (for data types with required deposition, see below). </li>
                            <li style="margin-top: 20px; margin-left: -20px;list-style: none;"><a href="#"></a>We encourage authors to ensure that their datasets are either deposited in publicly available repositories (where available and appropriate) or presented in the main manuscript or additional supporting files, in machine-readable format (such as spreadsheets rather than PDFs) whenever possible. Please see the Data repository guidance page for further information. For several journals, deposition of the data on which the conclusions of the manuscript rely is required. Please check the individual journal’s Submission Guidelines for more information.</li>
                            <li style="margin-top: 20px; margin-left: -20px;list-style: none;"><a href="#"></a>Authors who need help understanding our data sharing policies, finding a suitable data repository, or organising and sharing research data can access our Author Support portal for additional guidance.</li>
                            <h2 style="margin-top: 40px; margin-left: -20px; color: #1b3051; font-family: Arial, Helvetica, sans-serif;" id="Text">Text recycling<a href="editorial_policies.php" class="btn btn-success ms-2">Back to top</a></h2>
                            <div class="line1"></div>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none;"><a href="#"></a>Submission of a manuscript to a BMC journal implies that materials described in the manuscript, including all relevant raw data, will be freely available to any scientist wishing to use them for non-commercial purposes, without breaching participant confidentiality.</li>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none"><a href="#"></a>For all journals, BMC strongly encourages that all datasets on which the conclusions of the paper rely should be available to readers, and where there is a community established norm for data sharing, BMC mandates data deposition (for data types with required deposition, see below). </li>
                            <li style="margin-top: 20px; margin-left: -20px;list-style: none;"><a href="#"></a>We encourage authors to ensure that their datasets are either deposited in publicly available repositories (where available and appropriate) or presented in the main manuscript or additional supporting files, in machine-readable format (such as spreadsheets rather than PDFs) whenever possible. Please see the Data repository guidance page for further information. For several journals, deposition of the data on which the conclusions of the manuscript rely is required. Please check the individual journal’s Submission Guidelines for more information.</li>
                            <li style="margin-top: 20px; margin-left: -20px;list-style: none;"><a href="#"></a>Authors who need help understanding our data sharing policies, finding a suitable data repository, or organising and sharing research data can access our Author Support portal for additional guidance.</li>
                            <h2 style="margin-top: 40px; margin-left: -20px; color: #1b3051; font-family: Arial, Helvetica, sans-serif;" id="Peer">Peer review<a href="editorial_policies.php" class="btn btn-success ms-2">Back to top</a></h2>
                            <div class="line1"></div>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none;"><a href="#"></a>Submission of a manuscript to a BMC journal implies that materials described in the manuscript, including all relevant raw data, will be freely available to any scientist wishing to use them for non-commercial purposes, without breaching participant confidentiality.</li>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none"><a href="#"></a>For all journals, BMC strongly encourages that all datasets on which the conclusions of the paper rely should be available to readers, and where there is a community established norm for data sharing, BMC mandates data deposition (for data types with required deposition, see below). </li>
                            <li style="margin-top: 20px; margin-left: -20px;list-style: none;"><a href="#"></a>We encourage authors to ensure that their datasets are either deposited in publicly available repositories (where available and appropriate) or presented in the main manuscript or additional supporting files, in machine-readable format (such as spreadsheets rather than PDFs) whenever possible. Please see the Data repository guidance page for further information. For several journals, deposition of the data on which the conclusions of the manuscript rely is required. Please check the individual journal’s Submission Guidelines for more information.</li>
                            <li style="margin-top: 20px; margin-left: -20px;list-style: none;"><a href="#"></a>Authors who need help understanding our data sharing policies, finding a suitable data repository, or organising and sharing research data can access our Author Support portal for additional guidance.</li>
                            <h2 style="margin-top: 40px; margin-left: -20px; color: #1b3051; font-family: Arial, Helvetica, sans-serif;" id="Confidentiality">Confidentiality<a href="editorial_policies.php" class="btn btn-success ms-2">Back to top</a></h2>
                            <div class="line1"></div>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none;"><a href="#"></a>Submission of a manuscript to a BMC journal implies that materials described in the manuscript, including all relevant raw data, will be freely available to any scientist wishing to use them for non-commercial purposes, without breaching participant confidentiality.</li>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none"><a href="#"></a>For all journals, BMC strongly encourages that all datasets on which the conclusions of the paper rely should be available to readers, and where there is a community established norm for data sharing, BMC mandates data deposition (for data types with required deposition, see below). </li>
                            <li style="margin-top: 20px; margin-left: -20px;list-style: none;"><a href="#"></a>We encourage authors to ensure that their datasets are either deposited in publicly available repositories (where available and appropriate) or presented in the main manuscript or additional supporting files, in machine-readable format (such as spreadsheets rather than PDFs) whenever possible. Please see the Data repository guidance page for further information. For several journals, deposition of the data on which the conclusions of the manuscript rely is required. Please check the individual journal’s Submission Guidelines for more information.</li>
                            <li style="margin-top: 20px; margin-left: -20px;list-style: none;"><a href="#"></a>Authors who need help understanding our data sharing policies, finding a suitable data repository, or organising and sharing research data can access our Author Support portal for additional guidance.</li>
                            <h2 style="margin-top: 40px; margin-left: -20px; color: #1b3051; font-family: Arial, Helvetica, sans-serif;" id="Misconduct">Misconduct<a href="editorial_policies.php" class="btn btn-success ms-2">Back to top</a></h2>
                            <div class="line1"></div>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none;"><a href="#"></a>Submission of a manuscript to a BMC journal implies that materials described in the manuscript, including all relevant raw data, will be freely available to any scientist wishing to use them for non-commercial purposes, without breaching participant confidentiality.</li>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none"><a href="#"></a>For all journals, BMC strongly encourages that all datasets on which the conclusions of the paper rely should be available to readers, and where there is a community established norm for data sharing, BMC mandates data deposition (for data types with required deposition, see below). </li>
                            <li style="margin-top: 20px; margin-left: -20px;list-style: none;"><a href="#"></a>We encourage authors to ensure that their datasets are either deposited in publicly available repositories (where available and appropriate) or presented in the main manuscript or additional supporting files, in machine-readable format (such as spreadsheets rather than PDFs) whenever possible. Please see the Data repository guidance page for further information. For several journals, deposition of the data on which the conclusions of the manuscript rely is required. Please check the individual journal’s Submission Guidelines for more information.</li>
                            <li style="margin-top: 20px; margin-left: -20px;list-style: none;"><a href="#"></a>Authors who need help understanding our data sharing policies, finding a suitable data repository, or organising and sharing research data can access our Author Support portal for additional guidance.</li>
                            <h2 style="margin-top: 40px; margin-left: -20px; color: #1b3051; font-family: Arial, Helvetica, sans-serif;" id="Correction">Corrections and retractions<a href="editorial_policies.php" class="btn btn-success ms-2">Back to top</a></h2>
                            <div class="line1"></div>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none;"><a href="#"></a>Submission of a manuscript to a BMC journal implies that materials described in the manuscript, including all relevant raw data, will be freely available to any scientist wishing to use them for non-commercial purposes, without breaching participant confidentiality.</li>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none"><a href="#"></a>For all journals, BMC strongly encourages that all datasets on which the conclusions of the paper rely should be available to readers, and where there is a community established norm for data sharing, BMC mandates data deposition (for data types with required deposition, see below). </li>
                            <li style="margin-top: 20px; margin-left: -20px;list-style: none;"><a href="#"></a>We encourage authors to ensure that their datasets are either deposited in publicly available repositories (where available and appropriate) or presented in the main manuscript or additional supporting files, in machine-readable format (such as spreadsheets rather than PDFs) whenever possible. Please see the Data repository guidance page for further information. For several journals, deposition of the data on which the conclusions of the manuscript rely is required. Please check the individual journal’s Submission Guidelines for more information.</li>
                            <li style="margin-top: 20px; margin-left: -20px;list-style: none;"><a href="#"></a>Authors who need help understanding our data sharing policies, finding a suitable data repository, or organising and sharing research data can access our Author Support portal for additional guidance.</li>
                            <h2 style="margin-top: 40px; margin-left: -20px; color: #1b3051; font-family: Arial, Helvetica, sans-serif;" id="Appeal">Appeals and complaints<a href="editorial_policies.php" class="btn btn-success ms-2">Back to top</a></h2>
                            <div class="line1"></div>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none;"><a href="#"></a>Submission of a manuscript to a BMC journal implies that materials described in the manuscript, including all relevant raw data, will be freely available to any scientist wishing to use them for non-commercial purposes, without breaching participant confidentiality.</li>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none"><a href="#"></a>For all journals, BMC strongly encourages that all datasets on which the conclusions of the paper rely should be available to readers, and where there is a community established norm for data sharing, BMC mandates data deposition (for data types with required deposition, see below). </li>
                            <li style="margin-top: 20px; margin-left: -20px;list-style: none;"><a href="#"></a>We encourage authors to ensure that their datasets are either deposited in publicly available repositories (where available and appropriate) or presented in the main manuscript or additional supporting files, in machine-readable format (such as spreadsheets rather than PDFs) whenever possible. Please see the Data repository guidance page for further information. For several journals, deposition of the data on which the conclusions of the manuscript rely is required. Please check the individual journal’s Submission Guidelines for more information.</li>
                            <li style="margin-top: 20px; margin-left: -20px;list-style: none;"><a href="#"></a>Authors who need help understanding our data sharing policies, finding a suitable data repository, or organising and sharing research data can access our Author Support portal for additional guidance.</li>
                            <h2 style="margin-top: 40px; margin-left: -20px; color: #1b3051; font-family: Arial, Helvetica, sans-serif;" id="Collection">Collections and Special Issues<a href="editorial_policies.php" class="btn btn-success ms-2">Back to top</a></h2>
                            <div class="line1"></div>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none;"><a href="#"></a>Submission of a manuscript to a BMC journal implies that materials described in the manuscript, including all relevant raw data, will be freely available to any scientist wishing to use them for non-commercial purposes, without breaching participant confidentiality.</li>
                            <li style="margin-top: 20px; margin-left: -20px; list-style: none"><a href="#"></a>For all journals, BMC strongly encourages that all datasets on which the conclusions of the paper rely should be available to readers, and where there is a community established norm for data sharing, BMC mandates data deposition (for data types with required deposition, see below). </li>
                            <li style="margin-top: 20px; margin-left: -20px;list-style: none;"><a href="#"></a>We encourage authors to ensure that their datasets are either deposited in publicly available repositories (where available and appropriate) or presented in the main manuscript or additional supporting files, in machine-readable format (such as spreadsheets rather than PDFs) whenever possible. Please see the Data repository guidance page for further information. For several journals, deposition of the data on which the conclusions of the manuscript rely is required. Please check the individual journal’s Submission Guidelines for more information.</li>
                            <li style="margin-top: 20px; margin-left: -20px;list-style: none;"><a href="#"></a>Authors who need help understanding our data sharing policies, finding a suitable data repository, or organising and sharing research data can access our Author Support portal for additional guidance.</li>

                        </ul>

                    </div>


            </div>
            </nav>
        </div>
    </div>

    <?php include("footer.php"); ?>

</body>

</html>